#!/bin/python3

import sys

def leftRotation(a, d):
    for i in range(d):
        temp = a[0]
        for i in range(len(a)-1):
            a[i]=a[i+1]
        a[len(a)-1] = temp
    return a        

if __name__ == "__main__":
    n, d = input().strip().split(' ')
    n, d = [int(n), int(d)]
    a = list(map(int, input().strip().split(' ')))
    result = leftRotation(a, d)
    print (" ".join(map(str, result)))


